spring:
  profiles:
    active: default

  application:
    name: book-api

  config:
    import: optional:configserver:http://localhost:9000

  cloud:
    config:
      label: main

  datasource:
    url: jdbc:mysql://localhost:3306/55g_shop
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 201800878
