spring:
  profiles:
    active: default

  application:
    name: book-api

  config:
    import: optional:configserver:http://localhost:9000

  cloud:
    config:
      label: main

  datasource:
    url: jdbc:mysql://localhost:3306/[database_name]
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: [ username ]
    password: [ password ]

image:
  url: url
  appkey: appkey
  secretKey: secretKey
  thumbnail:
    path: "/55gshop/local/thumbnails/"

---
spring:
  config:
    activate:
      on-profile: dev

image:
  thumbnail:
    path: "/55gshop/book/thumbnails/"

---
spring:
  config:
    activate:
      on-profile: live
image:
  thumbnail:
    path: "/55gshop/live/thumbnails/"